id: I13B990D8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:40:28+00:00'
last_modified: '2022-06-09T08:01:34.892495+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2549
  title: འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་རྣམ་ཐར་སྐལ་བཟང་ཡིད་ཀྱི་གདུང་སེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B08B:
      image_group_id: I1CZ2727
      title: Volume 1 of 'gro 'dul dpa' bo rdo rje'i rnam thar skal bzang yid kyi
        gdung sel
      total_pages: 218
      order: 1
      base_file: B08B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
