id: I13B990D8
legacy_id: P007960
ocr_import_info:
  bdrc_scan_id: W1CZ2549
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T00:39:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:26:12.974714+00:00'
last_modified: 2022-08-31 03:26:35.697911
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2549
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2549
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་རྣམ་ཐར་སྐལ་བཟང་ཡིད་ཀྱི་གདུང་སེལ།
  author: ཨ་འཛོམ་རྒྱལ་སྲས་འགྱུར་མེད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6036170470430592
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I1CZ2727:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2727
      total_pages: 218
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2727.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6036170470430592
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
