id: P007960
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2549
  title: འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་རྣམ་ཐར་སྐལ་བཟང་ཡིད་ཀྱི་གདུང་སེལ
  author: ''
  volumes:
    78fd0fbe1fbb4b6793286020cd87743e:
      image_group_id: I1CZ2727
      title: ''
      volume_number: 1
      total_pages: 218
ebook_metadata:
  title: འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་རྣམ་ཐར་སྐལ་བཟང་ཡིད་ཀྱི་གདུང་སེལ
  author: ''
  sku: P007960
  cover: cover.jpg
  layers:
  - pagination
